name: freshstart
description: FreshStart Health Application
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  path: ^1.9.1
  fluttertoast: ^8.2.4
  flutter_secure_storage: ^9.2.4
  provider: ^6.0.0
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2
  google_fonts: ^6.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.0
  fl_chart: any
  tutorial_coach_mark: ^1.3.0
  permission_handler: ^12.0.0
  
  

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/android-chrome-512x512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/

