// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

  
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVPbomA2cVkGAxuhEYfppb2tHeajThIzE',
    appId: '1:1029181585413:web:b3781000e28fbdeb8e046c',
    messagingSenderId: '1029181585413',
    projectId: 'freshstart-3aefa',
    authDomain: 'freshstart-3aefa.firebaseapp.com',
    storageBucket: 'freshstart-3aefa.appspot.com',
    measurementId: 'G-VPQPL79V22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfXNkZG6lQmiShzLvh2ZNJF1lzXmp-SKs',
    appId: '1:1029181585413:android:6293a00e441e40018e046c',
    messagingSenderId: '1029181585413',
    projectId: 'freshstart-3aefa',
    storageBucket: 'freshstart-3aefa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLe6kllGKuXBmv5mO2pzRSbz6tn950A7w',
    appId: '1:1029181585413:ios:a9a84b54032655a98e046c',
    messagingSenderId: '1029181585413',
    projectId: 'freshstart-3aefa',
    storageBucket: 'freshstart-3aefa.appspot.com',
    iosBundleId: 'com.example.freshstart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLe6kllGKuXBmv5mO2pzRSbz6tn950A7w',
    appId: '1:1029181585413:ios:a9a84b54032655a98e046c',
    messagingSenderId: '1029181585413',
    projectId: 'freshstart-3aefa',
    storageBucket: 'freshstart-3aefa.appspot.com',
    iosBundleId: 'com.example.freshstart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVPbomA2cVkGAxuhEYfppb2tHeajThIzE',
    appId: '1:1029181585413:web:38fd11904fbe60d68e046c',
    messagingSenderId: '1029181585413',
    projectId: 'freshstart-3aefa',
    authDomain: 'freshstart-3aefa.firebaseapp.com',
    storageBucket: 'freshstart-3aefa.appspot.com',
    measurementId: 'G-ERJY7REC0D',
  );
}

